DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code INTEGER,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description VARCHAR(255),
    url_id BIGINT REFERENCES urls(id),
    created_at TIMESTAMP
);
